# This is a basic workflow to help you get started with Actions

name: Hello_world

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Enter text to print'
        type: string
      environment:
        description: 'Select the environment for deployment'
        type: environment
        
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: |
          echo "Hello, world!"
          echo "I am a reusable workflow comming from the Pipeline_server"
          echo "my task is to print the ${{ inputs.text }}"
          echo "${{ vars.USER_NAME }} has the phone munber = ${{ secrets.PHONE_NUMBER }}"
